### PR TITLE
Updating pluggable transport page to include instructions and a scree…

### PR DESCRIPTION
**Pull request by andpersand**
…nshot.

### CODE REVIEW

**Comment by emmapeel2** [comment]
merged!

**Review by emmapeel2 — CHANGES_REQUESTED** [review]
I like this paragraph, but I think it is somehow duplicating what we have in /transports https://tb-manual.torproject.org/transports/
would you like to have a look and merge those two?

**Comment by andpersand** [comment]
I'm not sure I understand completely - would you like me to remove the paragraph from one of the pages, or merge the transport and circumvention pages into one page?

**Comment by emmapeel2** [comment]
I think that for example the instructions should not duplicate what we have, but of course you can link to them, and update those instructions.
It is important that the information is not duplicated, otherwise it becomes exponentially harder to maintain and there are different versions of each doc, with different ages.

Please try to merge your contributions with the other docs, and in general try to get rid of any duplicated information.

**Pull request closed without merging**
