### PR TITLE
Add torrent warning to Known Issues (#26936)

### PR DESCRIPTION
**Pull request by traumschule**
https://bugs.torproject.org/26936

### CODE REVIEW

**Review by emmapeel2 — CHANGES_REQUESTED** [review]
Changes have to be done on the file content/known-issues/contents.lr, please never touch the +lang files because they are going to be overwritten with the l18n plugin.
Once you change the contents.lr file, when running 'lektor build' the other files are going to pick up the changes.

**Comment by traumschule** [comment]
Now i know, thanks! Fixed and rebased.

**Review by emmapeel2 — APPROVED** [review]
Yes, this is the right file thanks. I merged it, and on top i added a commit with the generated changes (ac9d9b5).

**Comment by traumschule** [comment]
So i guess this can be closed.

**Pull request closed without merging**
